
trigger: none

pool:
  name: vmss-devops-infra-01

steps:
- bash: |
      # Script adapted from https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux

      # Install required packages.
      sudo apt-get --assume-yes update
      sudo apt-get --assume-yes install ca-certificates curl apt-transport-https lsb-release gnupg

      # Download and install Microsoft signing key.
      sudo mkdir -p /etc/apt/keyrings
      curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
          gpg --dearmor |
          sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
      sudo chmod go+r /etc/apt/keyrings/microsoft.gpg

      # Add the Azure CLI software repo.
      AZ_REPO=$(lsb_release -cs)
      echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
          sudo tee /etc/apt/sources.list.d/azure-cli.list

      # Install azure-cli package.
      sudo apt-get --assume-yes update
      sudo apt-get --assume-yes install azure-cli
  displayName: "Install Azure CLI"

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy container registry'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: 'serviceconn-vssub'
    subscriptionId: 'd74666f0-bce7-4f76-bb70-c58f3b3c7bbe'
    resourceGroupName: 'rg-devops-infra'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '**/modules/container-registry.bicep'
    overrideParameters: '-name acrdevopscore2024 -sku Premium'
    deploymentMode: Incremental