
trigger: none

parameters:
- name: subscriptionId
  type: string
  default: "d74666f0-bce7-4f76-bb70-c58f3b3c7bbe"
- name: serviceConnectionName
  type: string
  default: "serviceconn-vssub"
- name: resourceGroupName
  type: string
  default: "rg-devops-infra"
- name: location
  type: string
  default: "West Europe"
- name: acrName
  type: string
  default: "acrdevopscore2024"
- name: acrSku
  type: string
  default: 'Premium'

pool:
  name: vmss-devops-infra-01

steps:
- template: ./templates/install-azure-cli.yml
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'deploy container registry'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: "${{ parameters.serviceConnectionName }}"
    subscriptionId: "${{ parameters.subscriptionId }}"
    resourceGroupName: ${{ parameters.resourceGroupName}}
    location: ${{ parameters.location }}
    templateLocation: "Linked artifact"
    csmFile: "**/modules/container-registry.bicep"
    overrideParameters: "-name ${{ parameters.acrName }} -sku ${{ parameters.acrSku}}"
    deploymentMode: Incremental