trigger: none

parameters:
- name: location
  type: string
  default: "westeurope"
- name: resourceGroupName
  type: string
  default: "rg-myapp"
- name: serviceConnectionName
  type: string
  default: "serviceconn-vssub"
- name: subscriptionId
  type: string
  default: "d74666f0-bce7-4f76-bb70-c58f3b3c7bbe"

pool:
  name: vmss-devops-infra-01

steps:
- template: ./templates/install-azure-cli.yml
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'deploy app service plan'
  inputs:
    deploymentScope: 'Resource Group'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: "${{ parameters.serviceConnectionName }}"
    subscriptionId: "${{ parameters.subscriptionId }}"
    resourceGroupName: ${{ parameters.resourceGroupName}}
    location: ${{ parameters.location }}
    templateLocation: "Linked artifact"
    csmFile: "./myapp-infra.bicep"
    deploymentMode: Incremental

  