trigger:
- main

pool:
  name: vmss-devops-infra-01

parameters:
- name: acrUrl
  type: string
  default: acrdevopscore2024.azurecr.io
- name: serviceConnectionName
  type: string
  default: "serviceconn-vssub"
steps:
- template: ./templates/install-azure-cli.yml
- task: AzureCLI@2
  displayName: "publish bicep files to ACR"
  inputs:
    azureSubscription: "${{ parameters.serviceConnectionName }}"
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      for filePath in $(Build.Repository.LocalPath)/modules/*.bicep; do
        [ -e "$filePath" ] || continue
        fileName=$(basename $filePath)
        moduleName="${fileName%.*}"
        moduleTag=":v1"
        echo "Pushing file $filePath as $moduleName$moduleTag into ${{ parameters.acrUrl }}"
        az bicep publish --file $filePath --target br:${{ parameters.acrUrl }}/bicep/modules/$moduleName$moduleTag --force
      done