trigger:
- main

pool:
  name: vmss-devops-infra-01

parameters:
- name: acrUrl
  type: string
  default: acrdevopscore2024.azurecr.io
steps:
- template: ./templates/install-azure-cli.yml
- task: AzureCLI@2
  displayName: "publish bicep files to ACR"
  inputs:
    azureSubscription: 'serviceconn-vssub'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      for filename in $(Build.Repository.LocalPath)/modules/*.bicep; do
        [ -e "$filename" ] || continue
        moduleName = $(basename $filename)
        echo "Pushing file $moduleName into $(acrUrl)"
        az bicep publish --file $module.FullName --target br:$(acrUrl)/bicep/modules/${$moduleName}
      done