trigger:
- main

pool:
  name: vmss-devops-infra-01

parameters:
- name: acrUrl
  type: string
  default: acrdevopscore2024.azurecr.io
steps:
#- task: AzureCLI@2
#  inputs:
#    azureSubscription: 'serviceconn-vssub'
#    scriptType: 'pscore'
#    scriptLocation: 'inlineScript'
#    inlineScript: |
#      $modules = Get-ChildItem -Path ../Modules/*.bicep -Recurse -Include *.bicep
#      foreach ($module in $modules)
#      {
#            $moduleName = $module.BaseName.ToLower()
#            Write-Host "Adding new module ${moduleName} with version $version"
#            az bicep publish --file $module.FullName --target br:acrdevopscore2024.azurecr.io/bicep/modules/${$moduleName}
#      }
- bash: |
      sudo apt-get --assume-yes update
      sudo apt-get --assume-yes install ca-certificates curl apt-transport-https lsb-release gnupg
      sudo mkdir -p /etc/apt/keyrings
      curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
          gpg --dearmor |
          sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
      sudo chmod go+r /etc/apt/keyrings/microsoft.gpg
      AZ_REPO=$(lsb_release -cs)
      echo "deb [arch=`dpkg --print-architecture` signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
          sudo tee /etc/apt/sources.list.d/azure-cli.list
      sudo apt-get --assume-yes update
      sudo apt-get --assume-yes install azure-cli
  displayName: "Install Azure CLI"
- task: AzureCLI@2
  inputs:
    azureSubscription: 'serviceconn-vssub'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      for filename in ./*.bicep; do
        [ -e "$filename" ] || continue
        $moduleName = $(basename $filename)
        echo "Pushing file $moduleName into $(acrUrl)
        az bicep publish --file $module.FullName --target br:$(acrUrl)/bicep/modules/${$moduleName}
      done