trigger:
- main

pool:
  name: vmss-devops-infra-01

parameters:
- name: acrUrl
  type: string
  default: acrdevopscore2024.azurecr.io
steps:
#- task: AzureCLI@2
#  inputs:
#    azureSubscription: 'serviceconn-vssub'
#    scriptType: 'pscore'
#    scriptLocation: 'inlineScript'
#    inlineScript: |
#      $modules = Get-ChildItem -Path ../Modules/*.bicep -Recurse -Include *.bicep
#      foreach ($module in $modules)
#      {
#            $moduleName = $module.BaseName.ToLower()
#            Write-Host "Adding new module ${moduleName} with version $version"
#            az bicep publish --file $module.FullName --target br:acrdevopscore2024.azurecr.io/bicep/modules/${$moduleName}
#      }

- task: AzureCLI@2
  inputs:
    azureSubscription: 'serviceconn-vssub'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      for filename in ./*.bicep; do
        [ -e "$filename" ] || continue
        $moduleName = $(basename $filename)
        echo "Pushing file $moduleName into $(acrUrl)
        az bicep publish --file $module.FullName --target br:$(acrUrl)/bicep/modules/${$moduleName}
      done